# Generated by Django 6.0.3 on 2026-04-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_b2c_fields'),
        ('payments', '0002_alter_transaction_options_transaction_description_and_more'),
    ]

    operations = [
    ]
