# Generated by Django 6.0.3 on 2026-04-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_kyc_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_support_staff',
            field=models.BooleanField(default=False, help_text='User can view and respond to support tickets'),
        ),
    ]
