# Generated by Django 6.0.2 on 2026-02-05 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Politics', 'Politics'), ('Economy', 'Economy'), ('Crypto', 'Crypto'), ('Environment', 'Environment')], max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('yes_probability', models.IntegerField(default=50)),
                ('volume', models.CharField(default='$0', max_length=100)),
                ('is_live', models.BooleanField(default=True)),
                ('end_date', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='markets.market')),
            ],
        ),
    ]
