# Generated by Django 6.0.2 on 2026-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='replies', to='markets.chatmessage'),
        ),
    ]
