# Generated by Django 6.0.3 on 2026-04-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_bet_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_probability', models.IntegerField()),
                ('no_probability', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='markets.market')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['market', 'timestamp'], name='markets_pri_market__d87867_idx')],
            },
        ),
    ]
