# Generated by Django 5.2.12 on 2026-04-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='option_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='option_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='market_type',
            field=models.CharField(choices=[('BINARY', 'Binary'), ('OPTION_LIST', 'Option List')], default='BINARY', max_length=20),
        ),
        migrations.AddField(
            model_name='market',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
