# Generated by Django 5.2.13 on 2026-04-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_bet_option_id_bet_option_label_market_market_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pricehistory',
            name='markets_pri_market__d87867_idx',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='option_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['market', 'option_id', 'timestamp'], name='markets_pri_market__430b09_idx'),
        ),
    ]
