# Generated by Django 5.2.12 on 2026-04-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0009_remove_pricehistory_markets_pri_market__d87867_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='is_bootstrapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='market',
            name='no_reserve',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='market',
            name='yes_reserve',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
