# Generated by Django 5.2.13 on 2026-04-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_lmsr_fields'),
        ('markets', '0007_fractional_shares'),
        ('markets', '0011_bet_order_status_bet_filled_at'),
    ]

    operations = [
    ]
