# Generated by Django 5.2.13 on 2026-04-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0012_merge_20260413_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='market',
            name='b',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='market',
            name='q_no',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='market',
            name='q_yes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='market',
            name='trading_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
