# Generated by Django 5.2.13 on 2026-04-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0013_alter_bet_quantity_alter_market_b_alter_market_q_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='is_bootstrapped',
        ),
        migrations.RemoveField(
            model_name='market',
            name='no_reserve',
        ),
        migrations.RemoveField(
            model_name='market',
            name='yes_reserve',
        ),
    ]
