# Generated by Django 5.2.13 on 2026-04-27 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0015_alter_bet_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_percent', models.FloatField(default=0.5)),
                ('withdrawal_fee_percent', models.FloatField(default=0.1)),
                ('early_withdrawal_penalty', models.FloatField(default=0.02)),
                ('total_yes_shares', models.FloatField(default=0.0)),
                ('total_no_shares', models.FloatField(default=0.0)),
                ('total_fees_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_unclaimed_fees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('market', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidity_pool', to='markets.market')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidityProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_provided', models.DecimalField(decimal_places=2, max_digits=15)),
                ('yes_shares_owned', models.FloatField(default=0.0)),
                ('no_shares_owned', models.FloatField(default=0.0)),
                ('total_fees_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fees_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unclaimed_fees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('last_fee_update', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='markets.liquiditypool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lp_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pool')},
            },
        ),
        migrations.CreateModel(
            name='FeeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('source_bet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='markets.bet')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_distributions', to='markets.liquiditypool')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_history', to='markets.liquidityprovider')),
            ],
        ),
    ]
