# Generated by Django 5.2.12 on 2026-04-10 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_actions', models.IntegerField(default=0)),
                ('creates', models.IntegerField(default=0)),
                ('updates', models.IntegerField(default=0)),
                ('deletes', models.IntegerField(default=0)),
                ('financial_actions', models.IntegerField(default=0)),
                ('admin_actions', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('total_amount_processed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('USER_PROFILE', 'User Profile'), ('BALANCE', 'User Balance'), ('TRANSACTIONS', 'Transaction History'), ('AUDIT_LOGS', 'Audit Logs'), ('ADMIN_PANEL', 'Admin Panel'), ('REPORTS', 'Reports'), ('API_KEY', 'API Key')], max_length=20)),
                ('resource_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('status_code', models.IntegerField(default=200)),
                ('success', models.BooleanField(default=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['resource_type', '-accessed_at'], name='audit_acces_resourc_c8f650_idx'), models.Index(fields=['user', '-accessed_at'], name='audit_acces_user_id_eac53b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('MULTIPLE_FAILED_LOGINS', 'Multiple Failed Logins'), ('UNUSUAL_BALANCE_CHANGE', 'Unusual Balance Change'), ('LARGE_WITHDRAWAL', 'Large Withdrawal'), ('ADMIN_ACCESS_OUTSIDE_HOURS', 'Admin Access Outside Hours'), ('RAPID_TRANSACTIONS', 'Rapid Transactions'), ('HASH_VERIFICATION_FAILED', 'Hash Verification Failed'), ('BULK_DATA_EXPORT', 'Bulk Data Export'), ('PERMISSION_ESCALATION', 'Permission Escalation'), ('DUPLICATE_TRANSACTION', 'Duplicate Transaction')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('description', models.TextField()),
                ('related_logs', models.JSONField(default=list)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', '-created_at'], name='audit_audit_severit_b73526_idx'), models.Index(fields=['acknowledged', '-created_at'], name='audit_audit_acknowl_a8ed41_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted'), ('DEPOSIT', 'Deposit Processed'), ('WITHDRAWAL', 'Withdrawal Processed'), ('BET_PLACED', 'Bet Placed'), ('MARKET_RESOLVED', 'Market Resolved'), ('PAYOUT_ISSUED', 'Payout Issued'), ('BALANCE_ADJUSTED', 'Balance Adjusted'), ('PERMISSION_CHANGED', 'Permission Changed'), ('LOGIN', 'User Login'), ('KYC_VERIFIED', 'KYC Verified'), ('ADMIN_ACTION', 'Admin Action'), ('SYSTEM_ACTION', 'System Action')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('content_type', models.CharField(max_length=255)),
                ('object_id', models.CharField(max_length=255)),
                ('object_repr', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('before_values', models.JSONField(blank=True, default=dict)),
                ('after_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('previous_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('current_hash', models.CharField(max_length=256, unique=True)),
                ('hash_verified', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('related_transaction', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_audit_logs', 'Can view audit logs'), ('export_audit_logs', 'Can export audit logs')],
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['object_id', '-created_at'], name='audit_audit_object__215966_idx'), models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'), models.Index(fields=['severity', '-created_at'], name='audit_audit_severit_49184d_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx')],
            },
        ),
    ]
