# Generated by Django 6.0.3 on 2026-04-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_05b4bc_idx',
            old_name='notification_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_427e4b_idx',
            old_name='notification_user_id_is_read_idx',
        ),
    ]
